[tool.poetry]
name = "instruqt_converter"
version = "0.0.2-rc.2"
description = "Python-based CLI utility to convert Instruqt tracks to and from a temporary state for testing"
authors = ["Nick Thompson <nick@imperial.org>"]
readme = "README.md"
homepage = "https://github.com/nsthompson/instruqt-converter"
license = "MIT"
include = [
    "LICENSE",
]
packages = [
    { include = "instruqt_converter" },
]

[tool.poetry.dependencies]
python = ">=3.13,<4.0.0"
rich-click = "*"
rich = "*"
python-frontmatter = "*"
PyYAML = "*"
gql = {extras = ["all"], version = "*"}
pydantic = ">=2"
pydantic-settings = ">=2"
frozenlist = "*"
multidict = "*"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "*"
flake8 = ">=7.3.0,<8.0.0"
black = ">=26.5.1,<27.0.0"
pre-commit = ">=4.6.0,<5.0.0"
pytest = ">=9.1.1,<10.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variables = [
    "instruqt_converter/__init__.py:__version__",
]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
build_command = "poetry build"
allow_zero_version = true
major_on_zero = false

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.devel]
match = "devel"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.publish]
upload_to_vcs_release = true

[tool.poetry.scripts]
convert = "instruqt_converter.convert:convert_track"


[tool.pytest.ini_options]
testpaths = ["tests"]
